# -*- coding: utf-8 -*-
"""IA2classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJki3Qg8lfpZGltdi3qMTPTdKjOvWmg5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

df=pd.read_csv('/content/winequality-red.csv')

df.head()

df.info()

df.describe(include='all')

df.isnull().sum()

df=df.fillna(0)

df.isnull().sum()

numerical_columns=df.select_dtypes(include=['float64']).columns
for column in numerical_columns:
  plt.figure(figsize=(10,4))
  sns.boxplot(df[numerical_columns])
  plt.show()

q1=df.quantile(0.25)
q3=df.quantile(0.75)
iqr=q3-q1
outliers=((df>q3+1.5*iqr)|(df<q1-1.5*iqr)).any(axis=1)
df=df[~outliers]

x=df.drop('quality',axis=1)
y=df['quality']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

y_pred

model=KNeighborsClassifier(n_neighbors=4)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

y_pred

print(accuracy_score(y_test,y_pred))