# -*- coding: utf-8 -*-
"""IA2_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6lCRnaplSQetJCokiz4d_ksVPYGrawl
"""

#1ans
import numpy as np
arr_1=np.array([1,4,2,6,9])
print(min(arr_1))
print(max(arr_1))
print(sum(arr_1))
print(np.mean(arr_1))
print(np.std(arr_1))

#2ans
import numpy as np
health_data = np.array([[160, 70, 30],
                        [165, 65, 35],
                        [170, 75, 40]])
print(np.mean(health_data))
print(np.std(health_data))

#3ans
import numpy as np
student_grades=[[[40,60,70],[20,30,90]]]
# I will get the last three subjects using index slicing.I will find exempt values having -1 using loc and replace them with 0,then i will calculate
#the average scores of students in those last three subjects.

#4ans
import numpy as np
temperature_data=np.linspace(15,25,24)
print(temperature_data)

#5ans
import numpy as np
daily_closing_prices = np.array([[100, 102, 98, 105, 107, 110],[108, 112, 115, 118, 120,156]])
window_size = 5
print(np.average(np.moveaxis(daily_closing_prices,1,1)))

#6ans
import numpy as np
arr=np.random.rand(100)
print(arr)

#7ans
import numpy as np
properties_matrix = np.array([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])
print(np.linalg.det(properties_matrix))

#8ans
arr_2=np.array([13,2,56,4,45])
#method 1
res_arr=[]
for value in arr_2:
  if value>5:
    res_arr.append(value)
print(res_arr)

#method 2
new_arr=[arr_2,arr_2>5]
print(new_arr)

#9ans
import pandas as pd
employee_data=pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
        'Age': [25, 30, 35, 40, 45, 50, 55],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami', 'Boston'],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR']})
print(employee_data[(employee_data['Age']<45)& (employee_data['Department']!='HR')]['Name'])

#10ans
import pandas as pd
sales_data=pd.DataFrame({'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Home Goods'],
        'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Sales': [70000, 50000, 30000, 40000, 60000]})
res=sales_data.groupby('Department')['Sales'].agg('mean')
print(res)

#11ans
import pandas as pd
supermarket_data=pd.DataFrame({
    'Product': ['Apples', 'Bananas', 'Cherries', 'Dates', 'Elderberries', 'Flour', 'Grapes'],
    'Category': ['Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Bakery', 'Fruit'],
    'Price': [1.20, 0.50, 3.00, 2.50, 4.00, 1.50, 2.00],
    'Promotion': [True, False, True, True, False, True, False]
})
avg_price_fruit_category=supermarket_data[(supermarket_data['Category']=='Fruit')]['Price'].agg('mean')
print(avg_price_fruit_category)
res=supermarket_data[(supermarket_data['Category']=='Fruit')& (supermarket_data['Promotion']=='False')& (supermarket_data['Price']>
                                                                                                         avg_price_fruit_category)]['Product']
print(res)

#12ans
import pandas as pd
df_1=pd.DataFrame({
    'Employee': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'Finance', 'IT'],
    'Manager': ['John', 'Rachel', 'Emily', 'Rachel']
})
df_2=pd.DataFrame({
    'Employee': ['Alice', 'Charlie', 'Eve'],
    'Project': ['P1', 'P3', 'P2']
})
res=pd.merge(df_1,df_2)
print(res)

#13ans
import pandas as pd
df_1=pd.read_csv('/content/Q13_sports_team_stats.csv')
avg_score_per_game=df_1.groupby('GamesPlayed')['Wins'].agg('mean')
print(avg_score_per_game)
df_1['WinRatio']=df_1['Wins']/df_1['GamesPlayed']
print(df_1)
print('Win ratios are determined for each team')

#14ans
import pandas as pd
customer=pd.read_csv('/content/Q14_customer_purchases.csv')
print(customer)
res=customer['PurchaseAmount'].agg('mean')
print(res)
print('There has been an increase in purchase amount after the loyalty program signup.')

#15ans
import pandas as pd
student_grades=pd.read_csv('/content/Q15_student_grades.csv')
res=student_grades.groupby('Subject')['Grade'].agg('mean')
print(res)
print('In History,the average score is a bit less.So,students need improvement in history subject. They are good at science subject.')