# -*- coding: utf-8 -*-
"""FinalAssessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WmyYT0GOslQ0ZCaPK-MAAHeOxN81Ijb3
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#1a)
df=pd.read_csv('/content/Final Dataset - IPL.csv')
print(df.head())

#1b)df.info()

df.shape

df.dtypes

#2a)
#I decided to find missing data and fill them with value 0 so no data will be lost from my dataset and it will
#be easy to perform analysis

print(df.isnull().head())
print(df.isnull().sum())
#if there are null values,i can fill them with 0 like this df.fillna(0)
# Here,we do not have null values in our data

#2b)
#to identify and resolve duplicate entries
print(df.duplicated().sum())
#there are no duplicate in data
#if there are duplicates,
df.drop_duplicates(inplace=True)

#3a)
df.describe()

#3a)
print(df['highscore'].mean())
print(df['highscore'].median())
print(df['highscore'].mode())
print(df['highscore'].var())
print(df['margin'].mean())
print(df['margin'].median())
print(df['margin'].mode())
print(df['margin'].var())

#4ans #finding which venue has been used for more times
df_1=df.groupby('venue')['match_id'].count()
print(df_1)
sns.barplot(df_1)

#4a)
df.groupby('match_winner')['match_winner'].value_counts().plot().grid()
print(df.groupby('match_winner')['match_winner'].value_counts())

#5ans
df.corr('second_ings_score','first_ings_score')
df.corr('high_score','second_ings_score')

#6ans
sns.boxplot(data=df,x='highscore',y='margin')
#I decided to continue with outliers as there are not much difference in outliers

sns.boxplot(data=df,y='first_ings_score',x='second_ings_score')

#7ans
df.groupby('toss_decision')['player_of_the_match'].count().plot()

#8ans
df.head(5)
print(df['player_of_the_match'].value_counts().nlargest(5))
res_df=df['player_of_the_match'].value_counts().nlargest(5)
sns.barplot(x=res_df.index,y=res_df)
plt.ylabel('No.of matches')
plt.show()

#9ans
#1) I have observed that gujarat won most of the matches and second place goes to rajasthan using a line graph
#2) The player who has recieved player of the match most of the times is kuldeep yadav
#3)Most of the matches are played in mumbai
#4)I have observed various measures of data like distribution of mean,median etc
#5)I have observed outliers in the given data
#6) I have observed correlation between different columns
#7) When one wins toss, which field is chosen most